name: Test

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
        node: [10, 12]
    env:
      CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn - install & build
        run: |
          yarn
          yarn run build-prod
          yarn run compile-test
      - name: Lint
        run: |
          yarn run lint
      - name: Run headless tests
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: npm run test
